# Generated by Django 2.2.7 on 2019-11-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_postcard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergallary',
            name='code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='send_postcard.VerifyCode'),
        ),
    ]
