# Generated by Django 2.2.7 on 2019-11-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191127_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='portrait',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Portrait'),
        ),
    ]
