# Generated by Django 2.2.7 on 2019-11-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191127_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='available_requiring_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='process_related_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sending_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
