# Generated by Django 2.2.7 on 2019-11-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191127_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergallary',
            options={'verbose_name_plural': 'UserGallaries'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='usergallary',
            name='own_image',
            field=models.ImageField(upload_to='postcards/'),
        ),
    ]
