# Generated by Django 2.2.7 on 2019-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191128_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallary',
            name='own_image',
            field=models.ImageField(unique=True, upload_to='postcards/'),
        ),
    ]
