# Generated by Django 2.2.7 on 2019-11-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191129_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallary',
            name='own_image',
            field=models.ImageField(upload_to='postcards/'),
        ),
    ]
