# Generated by Django 2.2.7 on 2019-12-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191130_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='add',
            field=models.TextField(default='', verbose_name='收件地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='available_requiring_num',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
