# Generated by Django 2.2.7 on 2019-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191205_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tmp_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergallary',
            name='own_image',
            field=models.ImageField(blank=True, null=True, upload_to='postcards/'),
        ),
        migrations.AlterField(
            model_name='usergallary',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
