# Generated by Django 2.2.7 on 2019-11-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191128_1959'),
        ('broad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserGallary')),
            ],
        ),
    ]
