# Generated by Django 2.2.7 on 2019-11-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broad', '0003_auto_20191129_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalgallary',
            name='img',
        ),
        migrations.AlterField(
            model_name='globalgallary',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='g_item', to='users.UserGallary'),
        ),
    ]
