# Generated by Django 2.2.7 on 2019-11-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_postcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randompeopleprocess',
            options={'verbose_name_plural': 'RandomPPlProcesses'},
        ),
        migrations.AddField(
            model_name='randompeopleprocess',
            name='code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='send_postcard.VerifyCode'),
        ),
    ]
