# Generated by Django 2.2.7 on 2019-12-05 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_postcard', '0002_auto_20191128_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='randompeopleprocess',
            name='expired_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='randompeopleprocess',
            name='code',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='send_postcard.VerifyCode'),
        ),
        migrations.AlterField(
            model_name='randompeopleprocess',
            name='remain_time',
            field=models.IntegerField(null=True),
        ),
    ]
